package com.danielabirzan.storemanagement.product.service;

import com.danielabirzan.storemanagement.product.dto.ProductRequest;
import com.danielabirzan.storemanagement.product.dto.ProductResponse;
import com.danielabirzan.storemanagement.product.model.Product;
import com.danielabirzan.storemanagement.product.repository.ProductRepository;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.ArgumentCaptor;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.test.util.ReflectionTestUtils;

import java.math.BigDecimal;
import java.util.List;
import java.util.NoSuchElementException;
import java.util.Optional;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
class ProductServiceTest {

    @Mock
    private ProductRepository productRepository;

    @InjectMocks
    private ProductService productService;

    // id is generated by JPA, so we set it via reflection for "persisted" fixtures
    private Product persistedProduct(Long id, String name, String description,
                                     BigDecimal price, Integer quantity) {
        Product product = new Product(name, description, price, quantity);
        ReflectionTestUtils.setField(product, "id", id);
        return product;
    }

    @Test
    void create_withValidRequest_savesProductAndReturnsResponse() {
        ProductRequest request = new ProductRequest("Milk", "1L", new BigDecimal("9.00"), 10);
        Product saved = persistedProduct(1L, "Milk", "1L", new BigDecimal("9.00"), 10);
        when(productRepository.save(any(Product.class))).thenReturn(saved);

        ProductResponse response = productService.create(request);

        assertThat(response.id()).isEqualTo(1L);
        assertThat(response.name()).isEqualTo("Milk");
        assertThat(response.description()).isEqualTo("1L");
        assertThat(response.price()).isEqualByComparingTo("9.00");
        assertThat(response.quantity()).isEqualTo(10);

        ArgumentCaptor<Product> captor = ArgumentCaptor.forClass(Product.class);
        verify(productRepository).save(captor.capture());
        Product captured = captor.getValue();
        assertThat(captured.getName()).isEqualTo("Milk");
        assertThat(captured.getPrice()).isEqualByComparingTo("9.00");
        assertThat(captured.getQuantity()).isEqualTo(10);
    }

    @Test
    void findById_whenProductExists_returnsProduct() {
        Product product = persistedProduct(1L, "Milk", "1L", new BigDecimal("9.00"), 10);
        when(productRepository.findById(1L)).thenReturn(Optional.of(product));

        ProductResponse response = productService.findById(1L);

        assertThat(response.id()).isEqualTo(1L);
        assertThat(response.name()).isEqualTo("Milk");
    }

    @Test
    void findById_whenProductNotFound_throwsNoSuchElementException() {
        when(productRepository.findById(99L)).thenReturn(Optional.empty());

        assertThatThrownBy(() -> productService.findById(99L))
                .isInstanceOf(NoSuchElementException.class)
                .hasMessageContaining("99");
    }

    @Test
    void findAll_whenProductsExist_returnsMappedList() {
        Product p1 = persistedProduct(1L, "Milk", "1L", new BigDecimal("9.00"), 10);
        Product p2 = persistedProduct(2L, "Bread", "white", new BigDecimal("5.45"), 20);
        when(productRepository.findAll()).thenReturn(List.of(p1, p2));

        List<ProductResponse> responses = productService.findAll();

        assertThat(responses).hasSize(2);
        assertThat(responses).extracting(ProductResponse::name)
                .containsExactly("Milk", "Bread");
    }

    @Test
    void findAll_whenRepositoryEmpty_returnsEmptyList() {
        when(productRepository.findAll()).thenReturn(List.of());

        List<ProductResponse> responses = productService.findAll();

        assertThat(responses).isEmpty();
    }

    @Test
    void changePrice_whenProductExists_updatesPrice() {
        Product product = persistedProduct(1L, "Milk", "1L", new BigDecimal("9.00"), 10);
        when(productRepository.findById(1L)).thenReturn(Optional.of(product));
        when(productRepository.save(any(Product.class))).thenAnswer(inv -> inv.getArgument(0));

        ProductResponse response = productService.changePrice(1L, new BigDecimal("7.50"));

        assertThat(response.price()).isEqualByComparingTo("7.50");
        assertThat(product.getPrice()).isEqualByComparingTo("7.50");
        verify(productRepository).save(product);
    }

    @Test
    void changePrice_whenProductNotFound_throwsNoSuchElementException() {
        when(productRepository.findById(99L)).thenReturn(Optional.empty());

        assertThatThrownBy(() -> productService.changePrice(99L, new BigDecimal("7.50")))
                .isInstanceOf(NoSuchElementException.class);

        verify(productRepository, never()).save(any());
    }

    @Test
    void changeQuantity_whenProductExists_updatesQuantity() {
        Product product = persistedProduct(1L, "Milk", "1L", new BigDecimal("9.00"), 10);
        when(productRepository.findById(1L)).thenReturn(Optional.of(product));
        when(productRepository.save(any(Product.class))).thenAnswer(inv -> inv.getArgument(0));

        ProductResponse response = productService.changeQuantity(1L, 25);

        assertThat(response.quantity()).isEqualTo(25);
        assertThat(product.getQuantity()).isEqualTo(25);
        verify(productRepository).save(product);
    }

    @Test
    void changeQuantity_whenProductNotFound_throwsNoSuchElementException() {
        when(productRepository.findById(99L)).thenReturn(Optional.empty());

        assertThatThrownBy(() -> productService.changeQuantity(99L, 25))
                .isInstanceOf(NoSuchElementException.class);

        verify(productRepository, never()).save(any());
    }

    @Test
    void delete_whenProductExists_deletesById() {
        when(productRepository.existsById(1L)).thenReturn(true);

        productService.delete(1L);

        verify(productRepository).deleteById(1L);
    }

    @Test
    void delete_whenProductNotFound_throwsNoSuchElementException() {
        when(productRepository.existsById(99L)).thenReturn(false);

        assertThatThrownBy(() -> productService.delete(99L))
                .isInstanceOf(NoSuchElementException.class);

        verify(productRepository, never()).deleteById(anyLong());
    }
}